version: 2

sources:
  - name: staging
    database: dtc-de-course-412616
    schema: ny_taxi

    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_tripdata
